#cloud-config
users:
  - name: ${username}
    passwd: ${password_hash}
    shell: /bin/bash
    lock_passwd: False
    ssh_pwauth: False
    chpasswd: { expire: False }
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: user,sudo
    ssh_authorized_keys:
      - ${ssh_pub_key}
keyboard:
  layout: de
package_update: true
packages:
  - qemu-system-agent
    #package_upgrade: true
    #package_reboot_if_required: true
ansible:
  package_name: ansible-core
  install_method: distro
  galaxy:
    actions:
      - [ansible-galaxy,role,install,wesmarcum.openssh]
      - [ansible-galaxy,role,install,geerlingguy.nginx]
  pull:
    url: https://github.com/dollervar/sf-tech-challenge.git
    playbook_name: ansible/sf-vm-playbook.yaml
    connection: local
